# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3355314424b83bbff7b582d7205542f6dbf3eb24c7e141f8471312d81750b0388ff03e362c1398484fbe460b1f40e2d4590e75ac4b4c0977291940d8e00a8b8

test:
  secret_key_base: 401d532d58bcf4e18e0c892a838b03aae3ffe20b4ebfac7df311f4fba2f649b657a6487897fe5e85de13a47727db80ce1bf3b6bb17720bd677b0d2a6616564bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
